
[phases.build]
    cmds = [
        "npm run build",
        "touch database/database.sqlite",
        "php artisan migrate --force"
    ]

[start]
    cmd = "php artisan queue:work --daemon & caddy run --config /etc/caddy/Caddyfile --adapter caddyfile & php-fpm -y /etc/php-fpm.conf"
